

attendees = ["Dennis", "Delta",
             "Marika", "Alexis", "Amber", "Isaac",
             "Jessica", "Doug", "Gabriel",
             "Joe", "Barbara", "Carl",
             "Alice", "Jeff", "Braeden", "Carter", "Tanner", "Coleman", "Brynlee",
             "Sam", "Erin", "Sariah", "Emma", "Hyrum",
             "Sitter1", "Sitter2"]


game_states = ( ("SETTING_UP", "No one here yet..."),
                ("FAMILY_PICTURES", "George's here with photographer (wands off, fireplace off, table twinkling)"),
                ("GROUP_PICTURES", "Everyone here with photographer (wands off, fireplace off, table twinkling)"),
                ("REGINA_ARRIVES", "Everyone should be gathered inside (wands off, fireplace fire, table twinkling)"),
                ("REGINA_EXPLAINS", "Bang!!! Regina is stuck in the fireplace. She explains and welcomes everyone. (wands off, fireplace talking, table twinkling)"),
                ("DINNER", "Everyone eats dinner (wands off, fireplace fire, table twinkling)"),
                ("FOGGER_WARMUP", "Fogger turns on.... (wands off, fireplace fire, table twinkling with fogger warming"),
                ("FOGGER_COUNTDOWN", "Red snake pattern (wands off, fireplace fire, table red snake with fogger warming"),
                ("POISONING", "Siren noise. Fog starts coming out (wands off, fireplace fire, table lightes off with fogger fogging)"),
                ("EVIL_ANNOUNCEMENT", "'I am the evil dark wizard Asmodean! You have invaded my domain and will be eliminated!'   (wands off, fireplace fire, table lights off, fogger fogging)"),
                ("CAST_PROHIBERE", "'<SIREN>Oh no! You are getting poisoned! Quick! Pick up your wands, give them a shake, and say PROHIBERE!' (wands buzzing, fireplace talking, table lights off, fogger fogging)"),
                ("WAIT_ON_PROHIBERE", "<SIREN>Wands turn on as people cast spell... (wands lighting, fireplace fire, table lights off, fogger fogging)"),
                ("FOGGER_OFF", "Enough people casted spell...siren off. (wands lit, fireplace fire, table lights off, fogger off)"),
                ("REGINAS_PLAN", "'Oh no!!! You have all been poisoned! We have to find the cure right away or the unimaginable could happen!' (wands off, fireplace talking)"),
                ("SPELL_BOOKS_APPEAR", "'Frigidarium!!! <POW!> Someone check the freezer, I just sent some help there!' (wands off, fireplace talking)"),
                ("PASS_OUT_BOOKS", "'Witch Weekly just had a delightful article on poisoning - I think it will do the trick!  Everyone get a copy!' (wands off, fireplace talking)"),
                ("ANTIDOTE_EXPLANATION", "'All you have to do is find out what poison was used, and then brew the antidote! It should be easy!'"),
                ("REGINA_SUGGESTS_PUMPKIN_CAKE", "I will get you started! The first thing you need is a food that has 'The Squib's Pumpkin' in it! Find it and everyone eat some!"),
                ("EATING_PUMPKIN_CAKE", "Everyone eats the cake"),
                ("REGINA_SAYS_YOU_ARE_POISONED", "'Okay, I hope that tasted good. Does anyone feel violently ill? If not, you have been poisoned.'"),
                ("REGINA_ASKS_IF_YOU_HAVE_DESERT_TOAD", "I think the next best thing would be to find some Desert Toad!"),
                ("WAIT_TO_FIND_TOAD", "Everyone looks for the toad"),
                ("REGINA_SAYS_THE_BRAVEST_MUST_EAT_IT", "'Since there is only one toad, we should find the bravest among us to eat it!' Everyone pick up your wands and cast 'FORTISSIMI'! Once again, that's FORTISSIMI"),
                ("CAST_FORTISSIMI", "Wands buzz"),
                ("WAIT_ON_FORTISSIMI", "Isaac's Wand lights up"),
                ("EAT_TOAD", "Isaac eats toad"),
                ("REGINA_SUGGESTS_KOUING_AMAN", "'Wonderful! Thank you to our brave helper! Next we need something that has Baneberry in it! Find some and eat it quick!'"),
                ("EAT_KOUING_AMAN", "Everyone eats Kouing Aman"),
                ("REGINA_SUGGESTS_POPCORN", "'I hope your copies of Witch Weekly are helping you narrow things down! Next I would eat something that has Korklump Juice in it!'"),
                ("EAT_POPCORN", "Eat Pop Rocks Dessert"),
                ("REGINA_SUGGESTS_COCKROACH_CLUSTERS", "'Next you should find something that has Pearl Dust in it! But don't eat it yet!'"),
                ("REGINA_EXPLAINS_RISUS_MAGNA", "'It looks like there isn't enough for everyone - I think the first people to master the 'RISUS MAGNA' spell should eat it' Everyone try to cast 'RISUS MAGNA'"),
                ("CAST_RISUS_MAGNA", "Everyone's wands buzz"),
                ("WAIT_ON_RISUS_MAGNA", "Only the Randall's wands light up..."),
                ("HYSTERICAL_LAUGHING", "Randall's eat Cockroach clusters and start laughing'"),
                ("REGINA_EXPLAINS_LINGUA_GUSTARE", "'Is there any Lichen Powder? Try sprinkling that on something really sweet. Oh! Don't forget to cast LINGUA GUSTARE before you eat it! Remember, sprinkle something sweet with the powder and cast LINGUA GUSTARE'"),
                ("CAST_LINGUA_GUSTARE", "Wands buzz"),
                ("WAIT_ON_LINGUA_GUSTARE", "Everyone's wands light up"),
                ("EAT_CAULDRON_CAKES", "Sprinkle powder on savory cupcakes, pass out, and eat."),
                ("REGINA_SAYS_FIND_DRAGONFLY_THORAX", "Is there anything that contains dragonfly thorax?"),
                ("FINDING_DRAGONFLY_THORAX", "Everyone finds the chocolate notes"),
                ("NOT_ENOUGH_NEED_THE_BEST_CANTANTA_CANTICUM_SPELL", "Hmm...it looks like there isn't enough! Only the best of singers should proceed! Everyone try casting 'CANTATA CANTICUM' once again, wave your wand and clearly say 'CANTATA CANTICUM'"),
                ("CAST_CANTATA_CANTICUM", "Wands Buzz"),
                ("WAIT_ON_CANTATA_CANTICUM", "Amber and Alexis' wands light up"),
                ("EAT_CHOCOLATE_KEYS", "They eat the chocolate keys"),
                ("PEDERSENS_SING", "They sing out the 'gaseous fire poison' song"),
                ("REGINA_DEPARTS_IN_A_RUSH_SAYS_USE_DENTIS_FORTIS", "'<SCREAM!!!!!> I'm in trouble! The dark wizard Asmodean has found me!!! I have to run. Quick find Fairy Teeth and cast DENTES FORTIS!!!! Goodbye!  <CRACK>"),
                ("CAST_DENTIS_FORTIS", "Wands buzz"),
                ("WAIT_ON_DENTIS_FORTIS", "Everyone's wands light up"),
                ("EAT_GOLD_ROCKS", "Everyone eats gold rocks"),
                ("CRAFT_CURE", "They find and brew the antidote...The end."))




